# Generated by Django 4.0.5 on 2022-09-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangmanapp', '0001_initial'),
    ]

    operations = [
        # Erstellt die GameWords Datenbanktabelle
        migrations.CreateModel(
            name='GameWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('difficulty', models.SmallIntegerField(default=1)),
            ],
        ),
        # Erstellt die Spieler Datenbanktabelle
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('wins', models.SmallIntegerField(default=0)),
                ('loses', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
