# Generated by Django 4.0.5 on 2022-09-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangmanapp', '0002_gamewords_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='AktivWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('hitLocations', models.CharField(max_length=200)),
            ],
        ),
    ]
