# Generated by Django 4.0.5 on 2022-09-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangmanapp', '0004_checkletters'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkletters',
            name='fails',
            field=models.SmallIntegerField(default=0),
        ),
    ]
