# Generated by Django 4.0.5 on 2022-09-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangmanapp', '0007_gametime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.CharField(max_length=500)),
            ],
        ),
    ]
